version: "3.8"

services:
  nextcloud:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    container_name: nextcloud-aio-mastercontainer
    ports:
      - 80:80
      - 8080:8080
      - 8443:8443
    environment:
      NEXTCLOUD_DATADIR: ${NEXTCLOUD_DATADIR}
      NEXTCLOUD_MOUNT: ${NEXTCLOUD_MOUNT}
      DOMAIN: ${LETSENCRYPT_HOST}
      EMAIL: ${LETSENCRYPT_EMAIL}
      LOG_FILE: "/data/access.log"
      # - BORG_RETENTION_POLICY="--keep-within=7d --keep-weekly=4 --keep-monthly=6"
      # - APACHE_PORT=11000
      # - APACHE_IP_BINDING=0.0.0.0
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer