services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "5000:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
    depends_on:
      - grampsweb_redis
    volumes:
      - ${GRAMPS_USERS}:/app/users  # persist user database
      - ${GRAMPS_INDEX}:/app/indexdir  # persist search index
      - ${GRAMPS_THUMBNAIL_CACHE}:/app/thumbnail_cache  # persist thumbnails
      - ${GRAMPS_CACHE}:/app/cache  # persist export and report caches
      - ${GRAMPS_SECRET}:/app/secret  # persist flask secret
      - ${GRAMPS_DB}:/root/.gramps/grampsdb  # persist Gramps database
      - ${GRAMPS_MEDIA}:/app/media  # persist media files
      - ${GRAMPS_TMP}:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO --concurrency=2

  grampsweb_redis:
    image: docker.io/library/redis:7.2.4-alpine
    container_name: grampsweb_redis
    restart: always

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
  gramps_tmp: